{% set version = "1.1.0" %}

package:
  name: tl-optional
  version: {{ version }}

source:
  url: https://github.com/TartanLlama/optional/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 88ece79f3de5ccaec4191951a222f95cc80c4381dafd3163bdb1ff87cedf3118
  patches:
    - bump_catch.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - ninja

test:
  commands:
    - test -f ${PREFIX}/include/tl/optional.hpp  # [not win]
    - test -f ${PREFIX}/share/cmake/tl-optional/tl-optional-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\tl\\optional.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\tl-optional\\tl-optional-config.cmake exit 1  # [win]

about:
  home: https://github.com/TartanLlama/optional
  license: CC0-1.0
  license_file: COPYING
  summary: C++11/14/17 std::optional with functional-style extensions and reference support

extra:
  recipe-maintainers:
    - traversaro
